export { MovingStrategy} from './MovingStrategy'
export { DiagonalMovingStrategy} from './DiagonalMovingStrategy'
export { KnightMovingStrategy} from './KnightMovingStrategy'
export { LineMovingStrategy} from './LineMovingStrategy'
export { PawnMovingStrategy} from './PawnMovingStrategy'