export { GameService} from './game-service'
export { CoordinateService} from './coordinate-service'
export { MovingService} from './moving-service'
export { MovingStrategies} from './moving-strategy-service'
export { NavigationService} from './navigation-service'
export { MoveType} from './move-type'
export { HistoryService} from './history-service'