import React  from 'react'

export const correctMovesOfQueen = (coordinate: Array<number>) => {
    const [column, field] = coordinate
    const moves: Array<Array<number>> = [
        [column - 1, field - 1],
        [column - 2, field - 2],
        [column - 3, field - 3],
        [column - 4, field - 4],
        [column - 5, field - 5],
        [column - 6, field - 6],
        [column - 7, field - 7],
        [column + 1, field - 1],
        [column + 2, field - 2],
        [column + 3, field - 3],
        [column + 4, field - 4],
        [column + 5, field - 5],
        [column + 6, field - 6],
        [column + 7, field - 7],
        [column - 1, field + 1],
        [column - 2, field + 2],
        [column - 3, field + 3],
        [column - 4, field + 4],
        [column - 5, field + 5],
        [column - 6, field + 6],
        [column - 7, field + 7],
        [column + 1, field + 1],
        [column + 2, field + 2],
        [column + 3, field + 3],
        [column + 4, field + 4],
        [column + 5, field + 5],
        [column + 6, field + 6],
        [column + 7, field + 7],
        [column, field + 1],
        [column, field + 2],
        [column, field + 3],
        [column, field + 4],
        [column, field + 5],
        [column, field + 6],
        [column, field + 7],
        [column, field - 7],
        [column, field - 6],
        [column, field - 5],
        [column, field - 4],
        [column, field - 3],
        [column, field - 2],
        [column, field - 1],
        [column - 1, field],
        [column - 2, field],
        [column - 3, field],
        [column - 4, field],
        [column - 5, field],
        [column - 6, field],
        [column - 7, field],
        [column + 1, field],
        [column + 2, field],
        [column + 3, field],
        [column + 4, field],
        [column + 5, field],
        [column + 6, field],
        [column + 7, field],
    ]

    return moves
}