import {Bishop, King, Knight, Pawn, Piece, Queen, Rook} from '../Arena_utils/chess-possible-move'

export const defaultChessArrangement: Array<Piece> = [
    new Pawn('white', 'A2', [1, 2], 'Pawn'),
    new Pawn('white', 'B2', [2, 2], 'Pawn'),
    new Pawn('white', 'C2', [3, 2], 'Pawn'),
    new Pawn('white', 'D2', [4, 2], 'Pawn'),
    new Pawn('white', 'E2', [5, 2], 'Pawn'),
    new Pawn('white', 'F2', [6, 2], 'Pawn'),
    new Pawn('white', 'G2', [7, 2], 'Pawn'),
    new Pawn('white', 'H2', [8, 2], 'Pawn'),
    new Pawn('black', 'A7', [1, 7], 'Pawn'),
    new Pawn('black', 'B7', [2, 7], 'Pawn'),
    new Pawn('black', 'C7', [3, 7], 'Pawn'),
    new Pawn('black', 'D7', [4, 7], 'Pawn'),
    new Pawn('black', 'E7', [5, 7], 'Pawn'),
    new Pawn('black', 'F7', [6, 7], 'Pawn'),
    new Pawn('black', 'G7', [7, 7], 'Pawn'),
    new Pawn('black', 'H7', [8, 7], 'Pawn'),
    new Rook('white', 'A1', [1, 1], 'Rook'),
    new Rook('white', 'A8', [8, 1], 'Rook'),
    new Rook('black', 'H1', [1, 8], 'Rook'),
    new Rook('black', 'H8', [8, 8], 'Rook'),
    new Knight('white', 'B1', [2, 1], 'Knight'),
    new Knight('white', 'G1', [7, 1], 'Knight'),
    new Knight('black', 'G8', [7, 8], 'Knight'),
    new Knight('black', 'B8', [2, 8], 'Knight'),
    new Bishop('white', 'C1', [3, 1], 'Bishop'),
    new Bishop('white', 'F1', [6, 1], 'Bishop'),
    new Bishop('black', 'C8', [3, 8], 'Bishop'),
    new Bishop('black', 'F8', [6, 8], 'Bishop'),
    new King('black', 'E8', [5, 8], 'King'),
    new King('white', 'E1', [5, 1], 'King'),
    new Queen('white', 'D1', [4, 1], 'Queen'),
    new Queen('black', 'D8', [4, 8], 'Queen')
]

