import {Figure} from '../types'

export const defaultChessArrangement: Array<Figure> = [
    {name: 'white-Rook', id: [1, 1], color: 'white'},
    {name: 'white-Pawn', id: [1, 2], color: 'white'},
    {name: 'black-Pawn', id: [1, 7], color: 'black'},
    {name: 'black-Rook', id: [1, 8], color: 'black'},
    {name: 'white-Knight', id: [2, 1], color: 'white'},
    {name: 'white-Pawn', id: [2, 2], color: 'white'},
    {name: 'black-Pawn', id: [2, 7], color: 'black'},
    {name: 'black-Knight', id: [2, 8], color: 'black'},
    {name: 'white-Bishop', id: [3, 1], color: 'white'},
    {name: 'white-Pawn', id: [3, 2], color: 'white'},
    {name: 'black-Pawn', id: [3, 7], color: 'black'},
    {name: 'black-Bishop', id: [3, 8], color: 'black'},
    {name: 'white-King', id: [4, 1], color: 'white'},
    {name: 'white-Pawn', id: [4, 2], color: 'white'},
    {name: 'black-Pawn', id: [4, 7], color: 'black'},
    {name: 'black-Queen', id: [4, 8], color: 'black'},
    {name: 'white-Queen', id: [5, 1], color: 'white'},
    {name: 'white-Pawn', id: [5, 2], color: 'white'},
    {name: 'black-Pawn', id: [5, 7], color: 'black'},
    {name: 'black-King', id: [5, 8], color: 'black'},
    {name: 'white-Bishop', id: [6, 1], color: 'white'},
    {name: 'white-Pawn', id: [6, 2], color: 'white'},
    {name: 'black-Pawn', id: [6, 7], color: 'black'},
    {name: 'black-Bishop', id: [6, 8], color: 'black'},
    {name: 'white-Knight', id: [7, 1], color: 'white'},
    {name: 'white-Pawn', id: [7, 2], color: 'white'},
    {name: 'black-Pawn', id: [7, 7], color: 'black'},
    {name: 'black-Knight', id: [7, 8], color: 'black'},
    {name: 'white-Rook', id: [8, 1], color: 'white'},
    {name: 'white-Pawn', id: [8, 2], color: 'white'},
    {name: 'black-Pawn', id: [8, 7], color: 'black'},
    {name: 'black-Rook', id: [8, 8], color: 'black'},
]

