import { Figure } from '../types'

export const defaultChessArrangement: Array<Figure> = [
    {id: 'A1', name: 'white-Rook', position: [1, 1], color: 'white'},
    {id: 'A2', name: 'white-Pawn', position: [1, 2], color: 'white'},
    {id: 'A7', name: 'black-Pawn', position: [1, 7], color: 'black'},
    {id: 'A8', name: 'black-Rook', position: [1, 8], color: 'black'},
    {id: 'B1', name: 'white-Knight', position: [2, 1], color: 'white'},
    {id: 'B2', name: 'white-Pawn', position: [2, 2], color: 'white'},
    {id: 'B7', name: 'black-Pawn', position: [2, 7], color: 'black'},
    {id: 'B8', name: 'black-Knight', position: [2, 8], color: 'black'},
    {id: 'C1', name: 'white-Bishop', position: [3, 1], color: 'white'},
    {id: 'C2', name: 'white-Pawn', position: [3, 2], color: 'white'},
    {id: 'C7', name: 'black-Pawn', position: [3, 7], color: 'black'},
    {id: 'C8', name: 'black-Bishop', position: [3, 8], color: 'black'},
    {id: 'D1', name: 'white-King', position: [4, 1], color: 'white'},
    {id: 'D2', name: 'white-Pawn', position: [4, 2], color: 'white'},
    {id: 'D7', name: 'black-Pawn', position: [4, 7], color: 'black'},
    {id: 'E8', name: 'black-Queen', position: [5, 8], color: 'black'},
    {id: 'E1', name: 'white-Queen', position: [5, 1], color: 'white'},
    {id: 'E2', name: 'white-Pawn', position: [5, 2], color: 'white'},
    {id: 'E7', name: 'black-Pawn', position: [5, 7], color: 'black'},
    {id: 'D8', name: 'black-King', position: [4, 8], color: 'black'},
    {id: 'F1', name: 'white-Bishop', position: [6, 1], color: 'white'},
    {id: 'F2', name: 'white-Pawn', position: [6, 2], color: 'white'},
    {id: 'F7', name: 'black-Pawn', position: [6, 7], color: 'black'},
    {id: 'F8', name: 'black-Bishop', position: [6, 8], color: 'black'},
    {id: 'G1', name: 'white-Knight', position: [7, 1], color: 'white'},
    {id: 'G2', name: 'white-Pawn', position: [7, 2], color: 'white'},
    {id: 'G7', name: 'black-Pawn', position: [7, 7], color: 'black'},
    {id: 'G8', name: 'black-Knight', position: [7, 8], color: 'black'},
    {id: 'H1', name: 'white-Rook', position: [8, 1], color: 'white'},
    {id: 'H2', name: 'white-Pawn', position: [8, 2], color: 'white'},
    {id: 'H7', name: 'black-Pawn', position: [8, 7], color: 'black'},
    {id: 'H8', name: 'black-Rook', position: [8, 8], color: 'black'},
]

