import {Figure} from '../types'

export const defaultChessArrangement: Array<Figure> = [
    {name: 'white-Rook', id: [0, 0], color: 'white'},
    {name: 'white-Pawn', id: [0, 1], color: 'white'},
    {name: 'black-Pawn', id: [0, 6], color: 'black'},
    {name: 'black-Rook', id: [0, 7], color: 'black'},
    {name: 'white-Knight', id: [1, 0], color: 'white'},
    {name: 'white-Pawn', id: [1, 1], color: 'white'},
    {name: 'black-Pawn', id: [1, 6], color: 'black'},
    {name: 'black-Knight', id: [1, 7], color: 'black'},
    {name: 'white-Bishop', id: [2, 0], color: 'white'},
    {name: 'white-Pawn', id: [2, 1], color: 'white'},
    {name: 'black-Pawn', id: [2, 6], color: 'black'},
    {name: 'black-Bishop', id: [2, 7], color: 'black'},
    {name: 'white-King', id: [3, 0], color: 'white'},
    {name: 'white-Pawn', id: [3, 1], color: 'white'},
    {name: 'black-Pawn', id: [3, 6], color: 'black'},
    {name: 'black-Queen', id: [4, 7], color: 'black'},
    {name: 'white-Queen', id: [4, 0], color: 'white'},
    {name: 'white-Pawn', id: [4, 1], color: 'white'},
    {name: 'black-Pawn', id: [4, 6], color: 'black'},
    {name: 'black-King', id: [3, 7], color: 'black'},
    {name: 'white-Bishop', id: [5, 0], color: 'white'},
    {name: 'white-Pawn', id: [5, 1], color: 'white'},
    {name: 'black-Pawn', id: [5, 6], color: 'black'},
    {name: 'black-Bishop', id: [5, 7], color: 'black'},
    {name: 'white-Knight', id: [6, 0], color: 'white'},
    {name: 'white-Pawn', id: [6, 1], color: 'white'},
    {name: 'black-Pawn', id: [6, 6], color: 'black'},
    {name: 'black-Knight', id: [6, 7], color: 'black'},
    {name: 'white-Rook', id: [7, 0], color: 'white'},
    {name: 'white-Pawn', id: [7, 1], color: 'white'},
    {name: 'black-Pawn', id: [7, 6], color: 'black'},
    {name: 'black-Rook', id: [7, 7], color: 'black'},
]

