export type { Figure } from './figure'
export type { Coordinate } from './coordinate'
export type { LastMove } from './lastMove'
export type { IsCheck } from './isCheck'
export type { MoveType } from './moveType'