export { setArrayToLocalStorage } from './local-storage-utils'
export { getItemFromLocalStorage } from './local-storage-utils'
export { removeChessFromLocalStorage } from './local-storage-utils'
export { getColorFromLocalStorage } from './local-storage-utils'
export { setCurrentColorToLocalStorage } from './local-storage-utils'